### ISSUE TITLE
Question about model

### ISSUE THREAD

**Issue by ljjsx** [yuvalkirstain/PickScore#10]
Hi, thanks for your amazing work, it helps me a lot.
I would like to know if there is any ready-made model checkpoint or API so that I can use the model directly without training. Because training is a bit difficult for me.
Thank you so much!

**Comment by yuvalkirstain** [comment]
yes sure, you can use the trained scoring function - https://huggingface.co/yuvalkirstain/PickScore_v1
and you can interact with with HF demo - https://huggingface.co/spaces/yuvalkirstain/PickScore
Feel free to close the issue if this answer's your question :)

**Comment by ljjsx** [comment]
> yes sure, you can use the trained scoring function - https://huggingface.co/yuvalkirstain/PickScore_v1 and you can interact with with HF demo - https://huggingface.co/spaces/yuvalkirstain/PickScore Feel free to close the issue if this answer's your question :)

Thank you so much! I will close the issue :)
