### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by sTiKyt** [yuvalkirstain/PickScore#11]
![image](https://github.com/yuvalkirstain/PickScore/assets/35602029/79e98394-fcbb-46a7-8f4c-ad1d62edbda0)

**Comment by yuvalkirstain** [comment]
Yes, we closed the website for the moment as we currently do not have funding for inference costs.

**Comment by manchuwook** [comment]
You should remove the link from the README.md file, it goes to a dangerous URL.

**Comment by yuvalkirstain** [comment]
@manchuwook done
