### ISSUE TITLE
Banned User List for dataset

### ISSUE THREAD

**Issue by lrzjason** [yuvalkirstain/PickScore#13]
Thanks for the great work. I have read your paper. It stated that the dataset would be filtered with banned user.
I am working on v2 dataset. Could you provide a banned user list for a reference?
After I filtered around 2000 pairs, I noticed some user might intented to choose the wrong choice.
I don't know if the banned user list would help to filter those 'bad user'.

Also, If I want to fine tune the model based on my filtered pairs, how should I prepare the dataset?
Apperciate for any advise.

**Comment by yuvalkirstain** [comment]
https://github.com/yuvalkirstain/heroku_app/blob/main/main.py#L114 - you can see here all the banned users. I also suggest to use some better word filter to find malicious users. Thank you so much, and can't wait to see you new cleaner version!

**Comment by lrzjason** [comment]
Thanks for reply. Very apperciated.
