### ISSUE TITLE
数据集的图像url地址还存在吗

### ISSUE THREAD

**Issue by learn01one** [yuvalkirstain/PickScore#16]
Hello, the url image address path of the data set seems to be invalid.

When trying to open any url, the following error is displayed：

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>G8W62N4SP7BPSK3V</RequestId>
<HostId>IjNJukKTLGUal5Y8yoULVQMo8laNUVzm6JiGs6n/anyaXz3ffZtTJ38X8k6W+IFsQaxq3d7lmBQ=</HostId>
</Error>

**Comment by yuvalkirstain** [comment]
Yes, we are temporarily not allowing to download from URL. Use the huggingface dataset?

**Comment by jbaron34** [comment]
The hugging face dataset has the same issue. The image urls listed in the dataset show access denied when attempting to download. Are the images themselves hosted on huggingface somewhere?

**Comment by yuvalkirstain** [comment]
Yes the jpg_0 and jpg_1 columns have the image bytes of the dataset

**Comment by yuvalkirstain** [comment]
@jbaron34 can you please confirm that is works?

**Comment by jbaron34** [comment]
Yes that works, not sure how I missed that. Thanks for your help!

**Comment by yuvalkirstain** [comment]
Great! @learn01one please close the issue?
