### ISSUE TITLE
how to only download text prompts

### ISSUE THREAD

**Issue by adwardlee** [yuvalkirstain/PickScore#26]
Hi @yuvalkirstain,

Great work! How to only download text prompts? Thanks.

**Comment by yuvalkirstain** [comment]
Hey! you have on huggingface datasets versions without images [`yuvalkirstain/pickapic_v1_no_images`](https://huggingface.co/datasets/yuvalkirstain/pickapic_v1_no_images), [`yuvalkirstain/pickapic_v2_no_images`](https://huggingface.co/datasets/yuvalkirstain/pickapic_v2_no_images).

You can download them and use only the text prompts. Enjoy!

**Comment by adwardlee** [comment]
Great. Thanks for your data.
