### ISSUE TITLE
Could you upload the json file of dataset? thx

### ISSUE THREAD

**Issue by midiexianghhh** [yuvalkirstain/PickScore#31]
I have downloaded the v1 dataset from hugging face, but I did not find the json file of the dataset, so that I can not load the dataset to train model. Could you share your json file with me? Thank you so much for you time.

**Comment by yuvalkirstain** [comment]
What do mean by json file of the dataset?

**Comment by midiexianghhh** [comment]
There are only parquet files in pickapic_v1 without json file, so that the dataloader can not read. Do you have the json of pickapic_v1?

**Comment by yuvalkirstain** [comment]
Have you tried following the instructions to download the dataset? 
If so, can you please share the error you get?
