### ISSUE TITLE
about unique dataset

### ISSUE THREAD

**Issue by huxian0402** [yuvalkirstain/PickScore#5]
Hi, I am interested in your work. The dataset is divided into the following parts: "train," "validation," "test," "validation_unique," and "test_unique." What is the difference between "validation" and "validation_unique"? and What is the difference between "test" and "test_unique"? @infoseceskimo @shahbuland @yuvalkirstain

**Comment by yuvalkirstain** [comment]
Hi! the different between `validation` and `validation_unique` is that `validation_unique` has only one example for each prompt (same for `test`).

**Comment by yuvalkirstain** [comment]
@huxian0402 if this answers your question please close the issue :)
