### ISSUE TITLE
The demo on huggingfaca shows runtime error.

### ISSUE THREAD

**Issue by nmbtwzt** [yuvalkirstain/PickScore#8]
Thank you for your efforts in this area, I'm interested in this area because it seems that this model can help to score the prompt and the corresponding image. 

But now the web demo shows runtime error, when will it be fixed please?

**Comment by yuvalkirstain** [comment]
Thanks for the issue, trying to restart the space.

**Comment by yuvalkirstain** [comment]
@nmbtwzt seems like it's working again, so you can close the issue?

**Comment by nmbtwzt** [comment]
Thanks for the fix, it's working fine now.
